### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by ustcwhy** [Cornell-RelaxML/quip-sharp#11]
Thanks for your wonderful work!
I try to compute the hessian of our custom model based on llama arch. But it reports the "RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method" while executing hessian_offline_llama.py", line 56, in forward_layer layer = layer.to(device). How to resolve this bug? Could you provide a version for disable mp since the code is quite complex?

**Comment by ustcwhy** [comment]
I forcefully set the start method to spawn:

if mp.get_start_method(allow_none=True) != 'spawn':
        mp.set_start_method('spawn', force=True)

**Comment by tsengalb99** [comment]
Hi,

Could you let us know what platform (os, arch, etc) you are running on? It would be helpful to know if we need to change anything to handle different systems, as we've only run this on x86 linux machines.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
