### ISSUE TITLE
Load LORA?

### ISSUE THREAD

**Issue by fahadh4ilyas** [Cornell-RelaxML/quip-sharp#16]
It seems that there is parameters named A and B in QuantizedLinear. I guess it's for LORA, right? How to load lora model inside? Was the LORA weight also quantized?

**Comment by tsengalb99** [comment]
A and B are leftovers from when we did a low rank correction (no fine tuning, this is purely offline) prior to quantization. We found that it was a worse use of bits than just increasing the codebook size.
