### ISSUE TITLE
mistral-7b

### ISSUE THREAD

**Issue by ehartford** [Cornell-RelaxML/quip-sharp#19]
can i please have example how to quantize mistral-7b?

**Comment by tsengalb99** [comment]
We already quantized mistral 7b, which is available at https://huggingface.co/relaxml. To quantize your own mistral 7b, you can run the quantize_llama.py script (instructions in readme) with relevant flags.

**Comment by ehartford** [comment]
Which flags?  Can you put example in the readme?

**Comment by ehartford** [comment]
Really don't understand why you close the issue when you didn't resolve it.

It is legitimate to ask for documentation.

**Comment by ehartford** [comment]
I'm not asking for a quantization I'm asking you to document how to do it

**Comment by tsengalb99** [comment]
Here are the exact commands:
1. Download the hessians from https://huggingface.co/relaxml/Hessians-Mistral-7b-4096
2. `python quantize_llama.py --save_path <save path> --codebook E8P12 --base_model mistralai/Mistral-7B-v0.1 --scale_override 0.9  --hessian_path <path to hessians>`
3. `python hfize_llama.py --quantized_path <save path from step 2> --hf_output_path <hf save path>`

`<hf save path>` should contain the quantized model in the huggingface format. The model file itself is in `//model/mistral.py`

**Comment by tsengalb99** [comment]
To generate the hessians:
`python hessian_offline.py --devset_size 4096 --ctx_size 8192 --base_model mistralai/Mistral-7B-v0.1 --save_path <hessian save path>`

**Comment by ehartford** [comment]
Thank you
