### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/worker/quip_llama2/hessians/2_qkv.pt'

### ISSUE THREAD

**Issue by Enjia** [Cornell-RelaxML/quip-sharp#21]
Hi I am trying to download Hessians of LLaMA 13B using download_hf.py, but it seems that 2_qkv.pt file is missing. Can you upload these pt files? Thanks!

**Comment by tsengalb99** [comment]
I'm seeing 2_qkv in both the llama 1 and llama 2 hessians in our HF repo. Which repo are you trying to download from?

**Comment by Enjia** [comment]
Sorry it's my bad, my downloading process is interrupted so I didn't get all the pt files
