### ISSUE TITLE
Does QUIP# support deepseek-llm-chat-67b?

### ISSUE THREAD

**Issue by Tint0ri** [Cornell-RelaxML/quip-sharp#23]
https://huggingface.co/deepseek-ai/deepseek-llm-67b-chat
 
I assume 2bits  should be fit into 24G GPU. I tried https://huggingface.co/LoneStriker/deepseek-llm-67b-chat-2.4bpw-h6-exl2 with 24G 3090. It works but very unstable.

**Comment by jerry-chee** [comment]
We currently do not, but it is relatively straightforward to adapt the code to quantize your intended model. Is this something you're interested in doing?

**Comment by Tint0ri** [comment]
I do want compare the 34B/4bits vs 67B/2bits. Deepseek is based on Llama. I think I can use quantize_llama.py to quantify the model. But I wonder how many VRAM need to run quantize_llama.py on a 67B model.

**Comment by tsengalb99** [comment]
You should be able to do everything on a 48GB card if the dimensions are the same as Llama 2 70b. There is one layer of 70b that requires running the quantization calculations in fp64, which increases memory consumption. If your 67b doesn't have that issue, then you probably only need ~30GB

**Comment by Tint0ri** [comment]
I only have 24GB card. So sad. I'd better wait for someone release the QUIP# version of Deepseek in HF.
Thanks.

**Comment by tsengalb99** [comment]
You should probably just try running the quantize script since the 67b dimensions might be sufficiently different for the pipeline to fit on a 24GB card. My memory estimates are also from a while ago  so they might be off.

**Comment by Tint0ri** [comment]
OK. I will try later. Tks.
