### ISSUE TITLE
Problem with namespace nvcuda

### ISSUE THREAD

**Issue by fernando-indrema** [Cornell-RelaxML/quip-sharp#24]
Hi! I am getting this error:

FAILED: /media/indrema/6372D35F27CA2C9A1/llama/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools.o 
/usr/local/cuda/bin/nvcc  -I/home/indrema/miniconda3/envs/quip/lib/python3.11/site-packages/torch/include -I/home/indrema/miniconda3/envs/quip/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/indrema/miniconda3/envs/quip/lib/python3.11/site-packages/torch/include/TH -I/home/indrema/miniconda3/envs/quip/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/indrema/miniconda3/envs/quip/include/python3.11 -c -c /media/indrema/6372D35F27CA2C9A1/llama/quip-sharp/quiptools/quiptools.cu -o /media/indrema/6372D35F27CA2C9A1/llama/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -g -Xcompiler -rdynamic -lineinfo -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
/media/indrema/6372D35F27CA2C9A1/llama/quip-sharp/quiptools/quiptools.cu(23): error: name must be a namespace name
  using namespace nvcuda;
                  ^

Any idea? (Cuda installed, 12.1)

**Comment by tsengalb99** [comment]
I haven't seen this before, can you post more information about your system?

**Comment by fernando-indrema** [comment]
nts
absl-py==2.0.0
accelerate==0.24.1
aiohttp==3.8.6
aiosignal==1.3.1
annotated-types==0.6.0
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
Brotli @ file:///work/ci_py311/brotli-split_1676830125088/work
certifi @ file:///croot/certifi_1700501669400/work/certifi
cffi @ file:///croot/cffi_1700254295673/work
chardet==5.2.0
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.1.7
colorama==0.4.6
cryptography @ file:///croot/cryptography_1702070282333/work
DataProperty==1.0.1
datasets==2.14.6
dill==0.3.7
distro==1.8.0
einops==0.7.0
fast-hadamard-transform==1.0.1
filelock @ file:///croot/filelock_1700591183607/work
flash-attn==2.3.4
frozenlist==1.4.0
fsspec==2023.10.0
glog==0.3.1
gmpy2 @ file:///work/ci_py311/gmpy2_1676839849213/work
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
huggingface-hub==0.17.3
idna @ file:///work/ci_py311/idna_1676822698822/work
Jinja2 @ file:///work/ci_py311/jinja2_1676823587943/work
joblib==1.3.2
jsonlines==4.0.0
lm-eval==0.3.0
MarkupSafe @ file:///work/ci_py311/markupsafe_1676823507015/work
mbstrdecoder==1.1.3
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
mpmath @ file:///croot/mpmath_1690848262763/work
multidict==6.0.4
multiprocess==0.70.15
networkx @ file:///croot/networkx_1690561992265/work
ninja==1.11.1.1
nltk==3.8.1
numexpr==2.8.7
numpy @ file:///croot/numpy_and_numpy_base_1701295038894/work/dist/numpy-1.26.2-cp311-cp311-linux_x86_64.whl#sha256=14973c61f3a96f31efa18449e9a0ba592baf1d942a48d1f461f877ee439e848f
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
openai==1.3.2
packaging==23.2
pandas==2.1.3
pathvalidate==3.2.0
Pillow @ file:///croot/pillow_1696580024257/work
portalocker==2.8.2
primefac==2.0.12
protobuf==4.25.1
psutil==5.9.6
pyarrow==14.0.1
pybind11==2.11.1
pycountry==22.3.5
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==2.5.1
pydantic_core==2.14.3
pyOpenSSL @ file:///croot/pyopenssl_1690223430423/work
PySocks @ file:///work/ci_py311/pysocks_1676822712504/work
pytablewriter==1.2.0
python-dateutil==2.8.2
python-gflags==3.1.2
pytz==2023.3.post1
PyYAML @ file:///croot/pyyaml_1698096049011/work
regex==2023.10.3
requests @ file:///croot/requests_1690400202158/work
rouge-score==0.1.2
sacrebleu==1.5.0
safetensors==0.4.0
scikit-learn==1.3.2
scipy==1.11.3
sentencepiece==0.1.99
six==1.16.0
sniffio==1.3.0
sqlitedict==2.1.0
sympy @ file:///croot/sympy_1701397643339/work
tabledata==1.3.3
tcolorpy==0.1.4
threadpoolctl==3.2.0
tokenizers==0.14.1
torch==2.1.1
torchaudio==2.1.1
torchvision==0.16.1
tqdm==4.66.1
tqdm-multiprocess==0.0.11
transformers==4.34.0
triton==2.1.0
typepy==1.3.2
typing_extensions @ file:///croot/typing_extensions_1690297465030/work
tzdata==2023.3
urllib3 @ file:///croot/urllib3_1698257533958/work
xxhash==3.4.1
yarl==1.9.2
zstandard==0.22.0

**Comment by fernando-indrema** [comment]
I was able to fix the error by adding to setup.py:
'nvcc': ['-O2', '-g', '-Xcompiler', '-rdynamic', '-lineinfo', '-arch=sm_89']})],

This error is related to enabling the compiler to understand which architecture it should target. In my case, my compute is equal to 8.9

**Comment by tsengalb99** [comment]
Which commit of the code are you on? We have all those flags except for arch sm_89 but that should be detected automatically.

**Comment by fernando-indrema** [comment]
I am on the latest. Sorry for how the way I write. I have just added arch_89. It seems it is not detecting it automatically. Anyways, after adding, it worked (considering my card is a rtx 4090)

**Comment by tsengalb99** [comment]
Great, glad you got it to work. Closing the issue since resolved.
