### ISSUE TITLE
distribute the memory usage evenly across both cards?

### ISSUE THREAD

**Issue by Minami-su** [Cornell-RelaxML/quip-sharp#26]
Parallel quantization of GPUs allows the distribution of memory usage across two graphics cards when running quantized code.
Quantizing a 34b model requires approximately 30GB, and I have two RTX 3090 cards with individual capacities of 24GB each, it is currently impossible to perform quantization on a single card. How can I distribute the memory usage evenly across both cards?

**Comment by tsengalb99** [comment]
The bottleneck in memory consumption during quantization is in the block_LDL call (https://github.com/Cornell-RelaxML/quip-sharp/blob/1d6e3c2d4c144eba80b945cca5429ce8d79d2cec/lib/algo/quip.py#L359). Specifically, block_LDL calls cholesky on the nxn Hessian matrix. Furthermore, the entire pipeline sometimes has to be run in fp64 (for example in the down layer of layer 8 of llama 2 70b), which doubles memory usage. I know that the entire pipeline can be run in fp64 on a single A6000, so you should be fine with two 24G cards as long as you can pool the memory. If you want to "pool" the memory you will need to find an alternative to torch cholesky that can share the memory of two GPUs. All the other ops will probably fit on one GPU but you might need to do some more aggressive host-device swapping than what I currently have.

**Comment by tsengalb99** [comment]
Also I forgot to mention that by default the script will parallelize across GPUs, so you will probably want to disable that if you need to pool GPUs to get more memory.
