### ISSUE TITLE
Question about error proxy in show_metrics

### ISSUE THREAD

**Issue by YangWang92** [Cornell-RelaxML/quip-sharp#29]
Hi all, 
Thanks for sharing such an interesting method, and I like your analysis and proof in the paper.

I have a question about the error proxy in the source code. 

I found that the optimziation object of PTQ to minimzie the sum of diag of $tr(\Delta W^T H \Delta W) = \sum \text{diag} (\Delta W^T H \Delta W)$.

<img width="548" alt="image" src="https://github.com/Cornell-RelaxML/quip-sharp/assets/3883941/cccdd0ec-a5a9-403a-b238-854f538c7993">

However, I found that the QuIP paper uses the following codes in evaluation codes. Is there any reason for the metric?

```python
    err_proxy = (((hatW - W_orig) @ H) * (hatW - W_orig)).sum() / ((W_orig @ H) * W_orig).sum()
```
https://github.com/Cornell-RelaxML/quip-sharp/blob/main/lib/utils/misc.py#L15

BTW, I guess should you use $\approx$ in the equation (1), $L(\hat{W}) \approx tr(\Delta W H \Delta W^T)$? 

Thanks!

Yang

**Comment by YangWang92** [comment]
Oh, I checked the formulation and found that $tr(\Delta W H Delta W^T)= (\Delta W @ H * \Delta W).sum()$，Thanks a lot!

**Comment by tsengalb99** [comment]
Correct, the implementation does the same thing as the math. We divide by WHW^T to normalize the proxy into a smaller, easier to read number.

**Comment by YangWang92** [comment]
> Correct, the implementation does the same thing as the math. We divide by WHW^T to normalize the proxy into a smaller, easier to read number.

BTW, I guess should you use $\approx$ in the equation (1), $L(\hat{W}) \approx tr(\Delta W H \Delta W^T)$?

**Comment by tsengalb99** [comment]
$WHW^T$ does not change within a layer so the thing being minimized is the same either way with or without the normalization.

**Comment by YangWang92** [comment]
> WHWT does not change within a layer so the thing being minimized is the same either way with or without the normalization.

I mean $tr(\Delta W H \Delta W^T)$ is the approximation of the loss function $L(\hat{W})$.

You can check details in the [paper](https://proceedings.mlr.press/v119/nagel20a.html). Eq.2 - 4

**Comment by tsengalb99** [comment]
Oh yes that should be fixed. Thanks for catching that.

**Comment by tsengalb99** [comment]
Ignore the other comment I sent - this equation is actually correct. H is defined as $E_x(x^Tx), x \in \mathbb{R}^{1 \times n}$ which is *interpreted* as the Hessian (see the paragraph below eq 1). We are minimizing this loss $\ell$ in the adaptive rounding (LDLQ) part of the quantization algorithm. $\ell$, which corresponds to eq 20 in the Nagel paper, is actually approximating eq 2 in the Nagel paper and is not being approximated itself.
