### ISSUE TITLE
llamafied model have some issues happening in hfize_llama.py

### ISSUE THREAD

**Issue by Minami-su** [Cornell-RelaxML/quip-sharp#30]
python quantize_llama.py --save_path Qwen-1_8B-Chat_LLaMAfied_2bitcc --base_model Qwen-1_8B-Chat_LLaMAfied/ --hessian_path hessians/llama2_70b/ --codebook E8P12 --scale_override 0.9 --batch_size 1 --devset_size 8 --ctx_size 500
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/5c09b27a-e7a3-4ba0-b9a9-981b3ff35f69)

python hfize_llama.py --quantized_path Qwen-1_8B-Chat_LLaMAfied_2bitcc/ --hf_output_path Qwen-1_8B-Chat_LLaMAfied_2bit

error:
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/37e9a8c7-b38c-4d3a-aa3c-f7bbe233e63a)
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/d6565c0e-07db-44c6-a20c-b4a53acb4d6a)
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/40265298-5348-42f2-94bf-1199efe8d483)

python interactive_gen.py --hf_path Qwen-1_8B-Chat_2bit --max_length 100
bad output:
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/4b9745b5-30ed-4a91-8d0c-5e78e4aa57db)

**Comment by tsengalb99** [comment]
The big block of text that says 'x was not initalized' is expected since we are loading an empty model in the beginning to copy the quantized weights over to. Your original (17) and quantized (19) perplexities seem very high in the quantization script. Are you sure your qwen to llama conversion is happening correctly? You may be missing some component of the model itself that is causing these high perplexities and poor generation output.

**Comment by Minami-su** [comment]
But I tested the original model and it worked
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/16bf9eb2-e4be-4403-8a2f-359f843caebd)
```
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer

tokenizer = AutoTokenizer.from_pretrained("Qwen-1_8B-Chat_LLaMAfied",trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("Qwen-1_8B-Chat_LLaMAfied", torch_dtype="auto", device_map="auto")
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

query = (
    "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n"
    "<|im_start|>user\nWho are you?<|im_end|>\n"
    "<|im_start|>assistant\n"
)
inputs = tokenizer([query], return_tensors="pt")
inputs = inputs.to("cuda")
generate_ids = model.generate(**inputs, eos_token_id=[151643, 151645], max_new_tokens=256, streamer=streamer)

```

**Comment by Minami-su** [comment]
> The big block of text that says 'x was not initalized' is expected since we are loading an empty model in the beginning to copy the quantized weights over to. Your original (17) and quantized (19) perplexities seem very high in the quantization script. Are you sure your qwen to llama conversion is happening correctly? You may be missing some component of the model itself that is causing these high perplexities and poor generation output.

I think ppl is normal because this is only a 1.8b model

**Comment by Minami-su** [comment]
The converted model can be used:
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/ce8f0cc5-c00e-4072-8617-6e9a89820929)

**Comment by Minami-su** [comment]
Then I tried the 7b model
python quantize_llama.py --save_path Qwen-7B-Chat_LLaMAfied_2bit --base_model Qwen-7B-Chat_LLaMAfied/ --hessian_path hessians/llama2_70b/ --codebook E8P12 --scale_override 0.9 --batch_size 1 --devset_size 8 --ctx_size 500
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/08320860-e7c3-4275-8d1e-58b0776f238f)
python hfize_llama.py --quantized_path Qwen-7B-Chat_LLaMAfied_2bit/ --hf_output_path Qwen-7B-Chat_LLaMAfied_2bit2
The same situation:
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/a8db7dbb-b6a2-4309-a30d-5b75fab0fa99)
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/86eaec5a-29ce-4c0a-a527-e182e59f442b)
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/9707b6de-d25c-46b0-a7df-ac607450c91a)
python interactive_gen2.py --hf_path Qwen-7B-Chat_LLaMAfied_2bit2
poor output:
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/b844ba5e-94b0-493c-a7ca-ba6294b532da)

**Comment by tsengalb99** [comment]
Did the comment the other person posted about Qwen in the other issue you opened help get Qwen to work?

**Comment by Minami-su** [comment]
> Did the comment the other person posted about Qwen in the other issue you opened help get Qwen to work?

That might work but it's gonna take some time

**Comment by Minami-su** [comment]
It's weird, obviously the model converted to llama works and no problem, but after quantization it doesn't work, maybe I need to train it and try again

**Comment by tsengalb99** [comment]
I think it is odd the perplexities are close to each other but the quantized version has poor generation output. Do the models we released on huggingface have good generation output?

**Comment by Minami-su** [comment]
> I think it is odd the perplexities are close to each other but the quantized version has poor generation output. Do the models we released on huggingface have good generation output on your side?

Yes, the model can output normally use llama 7b chat hf,

**Comment by Minami-su** [comment]
I would try to fine-tune the LLaMAfied model, then try to quantify it again, and if that didn't work out, I would have to continue with another problem approach

**Comment by tsengalb99** [comment]
Can you share a link to your qwen code again? If your setup is the same as ours, the converted Qwen -> Llama model uses the huggingface code while the quantized model uses a copy of that code with nn.Linear replaced with Fused/QuantizedLinear. This means that you're not running the same file when using the converted model vs the quantized model.

**Comment by Minami-su** [comment]
> Can you share a link to your qwen code again? If your setup is the same as ours, the converted Qwen -> Llama model uses the huggingface code while the quantized model uses a copy of that code with nn.Linear replaced with Fused/QuantizedLinear. This means that you're not running the same file when using the converted model vs the quantized model.

Do you mean the convert code ,qwen to llama？

**Comment by Minami-su** [comment]
new method to transform 'qwen' into 'llama' using the code available at https://github.com/hiyouga/LLaMA-Factory/blob/main/tests/llamafy_qwen.py.

**Comment by tsengalb99** [comment]
No your llama or qwen file similar to `model/llama.py` that swaps out nn.Linear with QuantizedLinear

**Comment by Minami-su** [comment]
> No your llama or qwen file similar to `model/llama.py` that swaps out nn.Linear with QuantizedLinear

Because I'm using the Llamafied model, the code is cloned from quip-sharp without any changes. Therefore, the llama.py file includes the use of QuantizedLinear.

**Comment by tsengalb99** [comment]
That is very interesting then. So you llamafy your Qwen model, quantize that with the existing code in our repo, and then that is giving garbage output? Are you on the latest code version and did you rebuild quiptools? We recently updated the cuda kernel which would affect your generation output if the index packing didn't match what the kernel expects. However since you're reporting the released llama models work fine that's probably not it.

**Comment by Minami-su** [comment]
![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/76865636/a15aaea7-9669-47ff-97f7-269f97edc711)

In fact, this situation also exists in the llama2_7b_chat_hf model, but the output results are good, and the perplexity (ppl) is normal. So, I'm thinking that it might be that the Llamafied model needs training to adapt to the llama model.

**Comment by Minami-su** [comment]
> That is very interesting then. So you llamafy your Qwen model, quantize that with the existing code in our repo, and then that is giving garbage output? Are you on the latest code version and did you rebuild quiptools? We recently updated the cuda kernel which would affect your generation output if the index packing didn't match what the kernel expects. However since you're reporting the released llama models work fine that's probably not it.

Yes,It's weird

**Comment by tsengalb99** [comment]
> ![image](https://private-user-images.githubusercontent.com/76865636/292991366-a15aaea7-9669-47ff-97f7-269f97edc711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjYwNjEsIm5iZiI6MTcwMzY2NTc2MSwicGF0aCI6Ii83Njg2NTYzNi8yOTI5OTEzNjYtYTE1YWFlYTctOTY2OS00N2ZmLTk3ZjctMjY5Zjk3ZWRjNzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA4MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OWVlYTU5NjAwOWZmOTgyNWVkZjJlZWE4YjIyY2I1YmRjYzdhMjk2YzllN2I2ZjA5ZmMwOGQxZGQ2OWI4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SNkjwLDAd56JTZaRBrtgmtS1xYl6teEKBrgGzU7gzXU)
> 
> In fact, this situation also exists in the llama2_7b_chat_hf model, but the output results are good, and the perplexity (ppl) is normal. So, I'm thinking that it might be that the Llamafied model needs training to adapt to the llama model.Perhaps the Llamafied model is not compatible with quip# , so I will try training the Llamafied model and then attempt quip# again.

This is expected. We load in an empty model in `hfize_llama.py` with nothing initialized and then copy all the data over (https://github.com/Cornell-RelaxML/quip-sharp/blob/1d6e3c2d4c144eba80b945cca5429ce8d79d2cec/hfize_llama.py#L60). Huggingface complains that nothing is initialized because indeed nothing is initialized.

**Comment by Minami-su** [comment]
https://huggingface.co/Minami-su/Qwen-7B-Chat_LLaMAfied
I upload this model you can try it

**Comment by Minami-su** [comment]
Alright.
https://github.com/QwenLM/Qwen/issues/891#issuecomment-1873122050
https://github.com/chu-tianxiang/QuIP-for-all
