### ISSUE TITLE
HF Mistral-7B and Llama 2 7b chat Not working. 

### ISSUE THREAD

**Issue by kklivil** [Cornell-RelaxML/quip-sharp#35]
Hello Team, I am experimenting with `E8P 2 Bit`, `E8P RVQ 3 Bit` and `E8P RVQ 4 Bit` versions of `Mistral-7B` and `Llama 2 7b chat` models for a text-generation task. The issues that I encountered are:

1. Gibberish output (Random characters) generated by the model.
2. Very long time to generate the output - around 5 minutes.
3. Very High GPU consumption: around 33 GB 

The issue is consistent with all three Lattice Codebooks.

I am directly using the HF model from your repo.
System detail:
OS: `Ubuntu 20.04.6 LTS x86_64` GPU: `NVIDIA A100 40 GB`

Code:
```import os
from langchain import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM
import transformers
import torch
from langchain.prompts import PromptTemplate, FewShotPromptTemplate
from langchain import LLMChain


model_name="relaxml/Mistral-7b-E8PRVQ-4Bit"
hf_access_token = "hf_XXXX" # Replace with your HF access token

tokenizer = AutoTokenizer.from_pretrained(
    model_name, use_auth_token=hf_access_token #, use_fast=True
)

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    device_map="auto",
    use_auth_token=hf_access_token,
)

pipeline = transformers.pipeline(
    "text-generation",  # task
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    use_fast=True,
    trust_remote_code=True,
    device_map="auto",
    max_length=4000,
    do_sample=True,
    top_k=3,
    num_return_sequences=1,
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=tokenizer.eos_token_id,
)

llm = HuggingFacePipeline(pipeline=pipeline, model_kwargs={"temperature": 0.0})

text_gen_intent_examples = [
{
"input_text": "please write a text to john saying I am running late",
"generated_text": "Hi John, I wanted to let you know that I'm running a bit late. I apologize for any inconvenience this may cause. I'll be there as soon as I can. Thanks for understanding,"
},
{
"input_text": "write text to Jessica saying the we have a meeting tomorrow",
"generated_text": "Hi Jessica, Just a reminder that we have a meeting scheduled for tomorrow. Please let me know if there's anything specific you'd like to discuss or prepare ahead of time. Looking forward to it!"
},
{
"input_text": "write a message to Patrick to send the presentation slides",
"generated_text": "Hi Patrick, Hope you're doing well. Could you please send over the presentation slides when you get a chance?"
}
]

text_gen_intent_prefix = """
[INST]
Generate a brief and concise text message or email that a person could quickly send while driving.
- It should be polite but direct, without any unnecessary details.
- your response must not be in chat format as shown below:
[/INST]
"""

prompt_template = """
<s>[INST]
input_text: {input_text}
generated_text: {generated_text}
</s>[/INST]
"""

prompt = PromptTemplate(
    template=prompt_template, input_variables=["input_text", "generated_text"]
)


few_shot_template = FewShotPromptTemplate(
    examples=text_gen_intent_examples,
    example_prompt=prompt,
    prefix=text_gen_intent_prefix,
    suffix="input_text: {input_text} \n generated_text:",
    input_variables=["input_text"],
    example_separator="\n\n",
)

llm_chain = LLMChain(prompt=few_shot_template, llm=llm)

text = """
       write an email to Mark stating I am running late for the meeting and won't be able to join. Also, to send the minutes of the
       meeting.
       """
output_lst = []

print(few_shot_template.format(input_text=text.strip()))
print("-" * 30)
time_list = []
iter_num = 5
import time
for i in range(iter_num):
    st_time = time.time()
    print(llm_chain.run(text.strip()))
    end_time = time.time()
    time_taken = end_time - st_time
    print(f' {time_taken=}')
    time_list.append(time_taken)
    print("-" * 30)

total_time_taken = sum(time_list)
avg_time = total_time_taken / len(time_list)
print(f"Average time taken = {round(avg_time, 2)}")
```
Output Generated:
```
utz cleohl cleufohlarrowarrowarrow orient appar cle indul appar cleailleöt士ötötightssndbugbugบohlufijioenohlohlohlufesser («ohlmulticol Barceluf Plus negarrow Negarrow Inf Infarrowarrow Infarrow Bedarrowaille Dead febrohlohlaille郎郎郎郎arrowiji sealbuglijbuglijlij PlusMSMbugbugbug Nutbugsndbugbugbugbug bleedingportal Negouthbugštštštštiekiekatoniek Contin Contin bleeding Continiekiekiekiekiek Brigiek бы Negwick бы Barcel original seal Negesseresseroke Barcelmulticolmulticolwick Barcel retro retro retro retroFF retro retro retroervicesieriiasmiasmiasmervicesunch plainiasmiasmervicesosoosoiasmiasmiasmwickINEwickbugbugwickwickót Barcel Barcelwickötwick Barcelwickšt Barcelwickwick Barcelwick notenwick Barcel org Barcel Barcel Barcel CL Barcel Barcel Barcel wides Barcelieriieritee absolutteeervicesieriieriieriulumieri Barcel absolutungsungswickwickwickwickwickwickvíervicesieriwickwickieriwickieriieriwickšt济œuverviceservices济erviceservicesoki CHAPTERitsch CHAPTERitschwickwick济
```

requirements.txt
```
transformers
torch
accelerate
bitsandbytes
xformers
langchain
scipy
```
Could you please help me with this?
Question: Do I need to train your models for a downstream task?

**NOTE:** The above code generates decent output with `non-quantized`, `nf4-quantized`, and `AWQ` version of `Mistral-7B` and `Llama 2 7b chat`

**Comment by tsengalb99** [comment]
The default transformers model does not use our QuantizedLinear layer. We have our own modified versions of transformers models that work in the same way but load QuIP# models. You can see interactive_gen.py in our code for how to load QuIP# models. Generation will be slow since huggingface generate does not work with CUDA graphs, which reduces the cost of launching CUDA kernels. We are working on switching to a different inference engine that has higher performance.

**Comment by tsengalb99** [comment]
this might also be useful for you https://huggingface.co/relaxml/Llama-2-70b-E8P-2Bit/discussions/2#657c4020688f1a0f7ed514a0

**Comment by kklivil** [comment]
Thanks for your reply. I am trying to run your example (interactive_gen.py) but the pip installation is failing.

```
pip install -r requirements.txt
Collecting flash-attn==2.3.4
  Using cached flash_attn-2.3.4.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1c28d6gn/flash-attn_85d2ef6802aa47b698772f21fd5c45a6/setup.py", line 8, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I tried installing `packaging` separately i.e. `pip install packaging` but then it failed with the error `ModuleNotFoundError: No module named 'wheel'` then I tried `pip install wheel` but then it again failed the error
`ModuleNotFoundError: No module named 'torch'`. I am not sure how to fix it. Could you please point to towards the solution?

Python version: `3.10.13`
OS: `Ubuntu 20.04.6 LTS`
NVIDIA Driver Version: `535.146.02`

CUDA version:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
Git log:
```
git log --oneline
8ec2f1a (HEAD -> main, origin/main, origin/HEAD) update doc
1673d81 update doc
1ac36c1 Merge pull request #34 from Cornell-RelaxML/patchc4
1284949 (origin/patchc4) patch c4
6a506a3 Update README.md
4674ace Merge pull request #33 from Cornell-RelaxML/release20240109
353e977 (origin/release20240109) no nofuse
fb3ca6a release
1d6e3c2 Merge pull request #20 from Cornell-RelaxML/release20231219
f729d8a (origin/release20231219) clean up
5cc9e04 fix readme
ebbfb9c pandoc
79b752f update
32a4687 Merge pull request #10 from Cornell-RelaxML/update_doc_d4
44072ea (origin/update_doc_d4) typo
afbb287 html
9928f75 remove d4
6648e56 deprecate D4
424ce01 Merge pull request #7 from Cornell-RelaxML/model_codebook_version
d08bfb2 (origin/model_codebook_version) revert
54b0870 update authors
e23b15e backup
855c9d4 update sample_devset() nproc==1 to run in serial, update quantize_llama.py to pass correct args to sample_devset()
90fd0d4 Update README.md
e22e1f6 Update README.md
84eb5c9 faster e8p kernel
e74a1f9 half int decompress
873e43a Merge pull request #3 from Cornell-RelaxML/release20231203
``

**Comment by tsengalb99** [comment]
>ModuleNotFoundError: No module named 'torch'
It looks like you don't have pytorch installed - can you install pytorch? https://pytorch.org/

**Comment by dandehavilland** [comment]
I'm having the same issue. `requirements.txt` includes `torch`, `packaging` etc. but the installation process fails.

Seems that the setup for some of the required modules happens before their dependencies are installed. Could be the order of the modules in `requirements.txt`?

**Comment by nprasanthi7** [comment]
pip install -r /data/Prasanthi/QuIP-for-all/requirements.txt
DEPRECATION: Loading egg at /data/Prasanthi/myenv/lib/python3.11/site-packages/quiptools_cuda-0.0.0-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: transformers in /data/Prasanthi/myenv/lib/python3.11/site-packages (from -r /data/Prasanthi/QuIP-for-all/requirements.txt (line 1)) (4.36.2)
Requirement already satisfied: accelerate in /data/Prasanthi/myenv/lib/python3.11/site-packages (from -r /data/Prasanthi/QuIP-for-all/requirements.txt (line 2)) (0.24.1)
Requirement already satisfied: torch in /data/Prasanthi/myenv/lib/python3.11/site-packages (from -r /data/Prasanthi/QuIP-for-all/requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: datasets in /data/Prasanthi/myenv/lib/python3.11/site-packages (from -r /data/Prasanthi/QuIP-for-all/requirements.txt (line 4)) (2.15.0)
Collecting fast-hadamard-transform (from -r /data/Prasanthi/QuIP-for-all/requirements.txt (line 5))
  Using cached fast_hadamard_transform-1.0.1.tar.gz (6.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/data/Prasanthi/myenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/Prasanthi/myenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/Prasanthi/myenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/Prasanthi/QuIP-for-all/quip_cuda/pip-build-env-fq6agwld/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/Prasanthi/QuIP-for-all/quip_cuda/pip-build-env-fq6agwld/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/data/Prasanthi/QuIP-for-all/quip_cuda/pip-build-env-fq6agwld/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/data/Prasanthi/QuIP-for-all/quip_cuda/pip-build-env-fq6agwld/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Even I am getting the same issue as @kklivil Kushagra. Could you please provide the solution?

**Comment by tsengalb99** [comment]
I will take a closer look later today.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tsengalb99** [comment]
I haven't forgotten about this yet - I got held up with some other stuff and will hopefully get to it today.

**Comment by tsengalb99** [comment]
I've regenerated requirements.txt and pushed a fix. Everything else is the same as before. The setup process works without issue on my machine but let me know if you're still running into issues with the new requirements.txt.

**Comment by tsengalb99** [comment]
Closing since no new activity. Feel free to reopen this issue if you still have questions.
