### ISSUE TITLE
TypeError: decompress_e8p_origorder(): incompatible function arguments.

### ISSUE THREAD

**Issue by KnutJaegersberg** [Cornell-RelaxML/quip-sharp#36]
I've used (not the version before the recent version as it came out during quantization) of quip-sharp to make 2 bit hessians of MoMo-72b (https://huggingface.co/moreh/MoMo-70B-LoRA-V1.4), a llamafied Qwen fine tuned on slimorca. 
I get an exception during the final step, which makes hf weigths from the quantized weights, as the script tries to load the weights. I also can't use the weights otherwise. 
For you to reproduce, I'm uploading the quantized (non-hf) weights here: 
https://huggingface.co/KnutJaegersberg/MoMo-72b-quants

The perplexity that is given at the end of the quantization was ok, like 7 up from 6.5, which let's me think that the weights are not completely broken. 

I add the complete exception below: 

I0113 09:07:36.679814 209425 hfize_llama.py:93] loading layer 79 down
I0113 09:07:36.699936 209425 hfize_llama.py:149] saving model...
The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
I0113 09:08:12.982370 209425 modeling.py:799] We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.40it/s]
I0113 09:08:19.277218 209425 hfize_llama.py:156] successfully loaded hfized model
I0113 09:08:19.277296 209425 hfize_llama.py:158] generating some text...
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Traceback (most recent call last):
  File "/run/media/knut/HD/quip-sharp/hfize_llama.py", line 177, in <module>
    main(args)
  File "/run/media/knut/HD/quip-sharp/hfize_llama.py", line 163, in main
    outputs = model.generate(input_ids=inputs['input_ids'].cuda(),
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/home/knut/transformers/lib/python3.9/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/model/llama.py", line 1086, in forward
    outputs = self.model(
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/model/llama.py", line 973, in forward
    layer_outputs = decoder_layer(
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/model/llama.py", line 682, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/model/llama.py", line 373, in forward
    qkv_states = self.qkv_proj(hidden_states.to(torch.float32))
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/lib/linear/quantized_linear.py", line 90, in forward
    return self.codebook_class(input,
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/knut/transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/run/media/knut/HD/quip-sharp/lib/codebook/latticee8_padded12.py", line 252, in forward
    quiptools_cuda.decompress_e8p_origorder(Qidxs, self.codebook.grid_abs,
TypeError: decompress_e8p_origorder(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor) -> None

Invoked with: tensor([[-15210,  24677, -15616,  ...,  24930,  26312,  26133],
        [ 26256,  21329,  13018,  ...,  28524,  24142,  31816],
        [-25804,   7775,    937,  ..., -18345,   9130,  -8142],
        ...,
        [-22927,  -1611, -31657,  ...,  -8611,  25484, -30339],
        [  9292, -27004,  28969,  ...,  17868,   7946, -11222],
        [ 25934,  -3162,  28537,  ...,  -4720,   8854,  21136]],
       device='cuda:0', dtype=torch.int16), tensor([[0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 1.5000],
        [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 2.5000],
        ...,
        [0.5000, 1.5000, 1.5000,  ..., 1.5000, 0.5000, 1.5000],
        [0.5000, 1.5000, 1.5000,  ..., 0.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 0.5000,  ..., 1.5000, 1.5000, 0.5000]],
       device='cuda:0', dtype=torch.float16), tensor([ True, False,  True, False,  True, False,  True, False, False,  True,
        False,  True, False, False,  True, False, False, False,  True, False,
         True, False, False,  True, False, False,  True, False,  True, False,
        False, False, False,  True, False,  True, False, False,  True, False,
        False,  True, False,  True, False, False,  True, False,  True,  True,
        False,  True, False, False, False, False, False,  True, False,  True,
        False, False,  True, False, False,  True, False,  True, False, False,
         True, False,  True,  True, False,  True, False, False,  True, False,
         True,  True, False,  True,  True,  True, False,  True, False, False,
        False, False, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True, False, False,  True, False,  True,
         True, False,  True, False, False,  True, False,  True,  True, False,
         True,  True,  True, False,  True, False, False,  True, False,  True,
         True, False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True, False, False, False, False, False, False, False,  True,
        False,  True, False, False,  True, False, False,  True, False,  True,
        False, False,  True, False,  True,  True, False,  True, False, False,
         True, False,  True,  True, False,  True,  True,  True, False,  True,
        False, False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True, False, False,  True,
        False,  True,  True, False,  True,  True,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,  True,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False], device='cuda:0'), tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float16)

![image](https://github.com/Cornell-RelaxML/quip-sharp/assets/17965169/e18536bf-51e8-4549-b7f3-c92e9e2fde3a)

**Comment by KnutJaegersberg** [comment]
Additionally before the script loads the layers, it outputs this info (about all layers it seems)

... long list of model layers...
attn.qkv_proj.Wscale', 'model.layers.64.self_attn.v_scale', 'model.layers.26.mlp.gate_scale', 'model.layers.66.mlp.down_proj.codebook_id', 'model.layers.61.self_attn.qkv_proj.SU', 'model.layers.22.mlp.up_scale', 'model.layers.69.mlp.gate_scale']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by tsengalb99** [comment]
> Additionally before the script loads the layers, it outputs this info (about all layers it seems)

This is expected since we are copying over data to an empty model.

What commit of the code are you on? And did you rebuild quiptools when you updated your code?

**Comment by KnutJaegersberg** [comment]
the date I find in the quiptools folder is 03. januari. I did not update the code since then, but it should work nonetheless?

**Comment by KnutJaegersberg** [comment]
I build quiptools on 3. januari.

**Comment by KnutJaegersberg** [comment]
the repo code might be from 18. december

**Comment by tsengalb99** [comment]
can you print the output of `git log`?

**Comment by KnutJaegersberg** [comment]
certainly, here it is: 



commit 32a4687cb2ba5f7e3921eefb2ec42836b7b1f8d9 (HEAD -> main, origin/main, origin/HEAD)
Merge: 6648e56 44072ea
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Dec 7 22:00:00 2023 -0500

    Merge pull request #10 from Cornell-RelaxML/update_doc_d4
    
    Update doc d4

commit 44072ea2aa312ba8f8ace1a77124d440e0553971 (origin/update_doc_d4)
Author: Albert <tsengalb99@gmail.com>
Date:   Thu Dec 7 21:59:06 2023 -0500

    typo

commit afbb287df4bd670c32ed8e81236264022d8283da
Author: Albert <tsengalb99@gmail.com>
Date:   Thu Dec 7 21:57:45 2023 -0500

    html

commit 9928f75758b89a903fd5f8804eae45009da06694
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Fri Dec 8 02:52:48 2023 +0000

    remove d4

:...skipping...
commit 32a4687cb2ba5f7e3921eefb2ec42836b7b1f8d9 (HEAD -> main, origin/main, origin/HEAD)
Merge: 6648e56 44072ea
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Dec 7 22:00:00 2023 -0500

    Merge pull request #10 from Cornell-RelaxML/update_doc_d4
    
    Update doc d4

commit 44072ea2aa312ba8f8ace1a77124d440e0553971 (origin/update_doc_d4)
Author: Albert <tsengalb99@gmail.com>
Date:   Thu Dec 7 21:59:06 2023 -0500

    typo

commit afbb287df4bd670c32ed8e81236264022d8283da
Author: Albert <tsengalb99@gmail.com>
Date:   Thu Dec 7 21:57:45 2023 -0500

    html

commit 9928f75758b89a903fd5f8804eae45009da06694
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Fri Dec 8 02:52:48 2023 +0000

    remove d4

commit 6648e56c126e512652407cd06936c9c1b5c3a595
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Wed Dec 6 20:57:52 2023 -0500

    deprecate D4

commit 424ce0109a07d4dfde1b2ab2e016a75b932ea70c
Merge: 54b0870 d08bfb2
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Wed Dec 6 14:18:26 2023 -0500

    Merge pull request #7 from Cornell-RelaxML/model_codebook_version
    
    model and codebook version check

commit d08bfb25c6c65e82b02c38587e02ffbc1735987b (origin/model_codebook_version)
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Wed Dec 6 19:18:12 2023 +0000

    revert

commit 54b087055b85826e8260dd97bd5f3fcc713847d3
Author: Jerry Chee <Jerry9567@gmail.com>
Date:   Wed Dec 6 13:52:45 2023 -0500

    update authors

commit e23b15e077e9f0d540c17aa256a41828e7d7682a
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Wed Dec 6 18:45:01 2023 +0000

    backup

commit 855c9d4de733b160e4637131ab63ced0c89e88d5
Author: Jerry Chee <Jerry9567@gmail.com>
Date:   Wed Dec 6 02:29:03 2023 -0500

    update sample_devset() nproc==1 to run in serial, update quantize_llama.py to pass correct args to sample_devset()

commit 90fd0d473e255f282e1631d2d2e796593c187239
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Mon Dec 4 11:21:57 2023 -0500

    Update README.md
    
    instructions for non llama models

commit e22e1f6e00bdcb287684a8e8061e11c3c499b3db
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Mon Dec 4 10:43:41 2023 -0500

    Update README.md
    
    hessian fp64 warning

commit 84eb5c9a2ec1e5c95176d61b54986234650996f9
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Mon Dec 4 03:40:06 2023 +0000

    faster e8p kernel

commit e74a1f931e2c7f055d83c1442696db832c1ee8dd
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Dec 3 23:57:39 2023 +0000

    half int decompress

commit 873e43a2baf97cfadf9c3baf863319d9795d918d
Merge: 515d87d e31aa66
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Sun Dec 3 16:08:46 2023 -0500

    Merge pull request #3 from Cornell-RelaxML/release20231203
    
    release update 20231203

commit e31aa66316fb2a937d81ddde18a213cd259d5877 (origin/release20231203)
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Dec 3 21:04:46 2023 +0000

    tune cutoff

commit 0928595b2976e1a3157b9f78c225d57401a76a2c
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Dec 3 20:43:12 2023 +0000

    gen speed

commit e52ae972860a64b2c2e6cbb724f80bcc8654ef40
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Dec 3 20:18:47 2023 +0000

    restore license

commit 2ddaccf5682726929fd31600736d4b0f365895f8
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Dec 3 20:15:17 2023 +0000

    release update

commit 515d87d534eda426793a8033f6736d5297fe9c10
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Thu Nov 30 20:10:00 2023 +0000

    remove sm86 flag

commit 75083f8fb4b3265ef3e1ed92f8ab2e3f9b8c88ff
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Thu Nov 30 20:09:17 2023 +0000

    minor bug fixes

commit 52b9a057465f12c72b2eecbe75b845031f4b6503
Merge: d8c8c67 95389af
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Nov 30 12:27:39 2023 -0500

    Merge pull request #1 from chaosagent/gemv
    
    chaosagent optimizations

commit 95389af623175e136df8d36584a523a0f76f06c8
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 04:05:04 2023 -0800

    shared codebook

commit e7722f0c30269962fce79c371c05d1d29f42706a
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 03:40:24 2023 -0800

    accum stuff

commit fa971e34994c944c1e61d95312fb8982fe5b986f
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 02:21:53 2023 -0800

    idk

commit 2b5f901a4fc0c26409344d238577aced99a36d17
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 01:45:33 2023 -0800

    local_n

commit f7a83cf6d8e69fb2ba64fd86729590b988f9e1f2
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 00:32:19 2023 -0800

    unroll_n

commit 50bea65136ae0af52281922631e698f5a4a63496
Author: David Hou <david.hou314@gmail.com>
Date:   Thu Nov 30 00:15:12 2023 -0800

    small changes (rtx3090)

commit d8c8c678242b40f71954cdea6c741b4ad1953115
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Nov 30 00:28:27 2023 -0500

    typo

commit 0151c07f51fe7a329f736fd36771237af70def32
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Nov 30 00:27:27 2023 -0500

    Update README.md with license info

commit d2311a8fbb6116e8ef1fca526b341a87d1e89ae2
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Thu Nov 30 00:16:26 2023 -0500

    Update README.md with chat models

commit db70abef45c60ee6c77df6663ad11e4d5684bcac
Author: Albert Tseng <albert@cr-a100-80-hn.identity.together.xyz>
Date:   Mon Nov 27 21:04:13 2023 +0000

    small optimization

commit 908a58423146b82052afea8897853a307cc46dc2
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Sun Nov 26 04:01:24 2023 +0000

    no graph in zero shot tasks

commit 4c29e0906b9f03cab1717251e7f5671f09287274
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Fri Nov 24 05:47:06 2023 +0000

    change matvec cutoff

commit 618a258789e51bbc88949b74550afcc6ae849684
Merge: dd4cbb5 bedc5b3
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Thu Nov 23 06:24:12 2023 +0000

    Merge branch 'main' of github.com:Cornell-RelaxML/quip-sharp into main

commit dd4cbb51fbc569468f21b5e3e15fb1e5f2ffd213
Author: Albert Tseng <albert@cr-a100-80-0003.identity.together.xyz>
Date:   Thu Nov 23 06:24:02 2023 +0000

    change chatbot to use contrastive sampling

commit bedc5b3d8dfbcf0f0944457f2c057822c1c25e82
Author: Jerry Chee <Jerry9567@gmail.com>
Date:   Wed Nov 22 23:36:58 2023 -0600

    update README to download hessians

commit adc8f016c9b1e04ae916a9be97aa6f49d93357d4
Author: Albert <tsengalb99@gmail.com>
Date:   Thu Nov 23 00:01:26 2023 -0500

    change U to mathbbH

commit 0434db6d4e792c41dea665e9a7e058b6a7230d0f
Author: Jerry Chee <Jerry9567@gmail.com>
Date:   Wed Nov 22 22:36:16 2023 -0600

    updating RHT in index

commit e9253420136540eeb4c10804706fc97ef93e5686
Author: Albert Tseng <33385672+tsengalb99@users.noreply.github.com>
Date:   Wed Nov 22 22:27:38 2023 -0500

    Create LICENSE

commit 4ac04d27d198a263b3661aff1ab5808c47f39ba4
Author: Albert <tsengalb99@gmail.com>
Date:   Wed Nov 22 22:24:48 2023 -0500

    release
(END)

**Comment by tsengalb99** [comment]
That's pretty out of date but all of our commits should be self contained. I'm not sure why you are seeing this error on this model but not the other ones you quantized. Can you try rebuilding quiptools and making sure something did not get corrupted?

**Comment by KnutJaegersberg** [comment]
I did that and I think it solved the problem, though I still have issues using the model in textgen webui.

**Comment by tsengalb99** [comment]
> though I still have issues using the model in textgen webui.

What issues are you seeing there? I haven't used webui before so I probably can't help there but oobagoob might.
