### ISSUE TITLE
Pytorch dequantization

### ISSUE THREAD

**Issue by JeevanBhoot** [Cornell-RelaxML/quip-sharp#40]
Do you have a python/Pytorch implementation of the dequantization (/scaling) that is done at inference time?

**Comment by tsengalb99** [comment]
Yes,  see https://github.com/Cornell-RelaxML/quip-sharp/blob/1c7ff15ddb8f31c6073757441ed0e6fded00bee2/lib/codebook/latticee8_padded12.py#L225. I didn’t write the actual dequantization up in Pytorch but its essentially the reverse of the packing in https://github.com/Cornell-RelaxML/quip-sharp/blob/1c7ff15ddb8f31c6073757441ed0e6fded00bee2/lib/codebook/latticee8_padded12.py#L187 to get entries in E8P and then a lookup, some sign operations, and a shift.

 

From: Jeevan ***@***.***> 
Sent: Monday, February 5, 2024 8:23 AM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] Pytorch dequantization (Issue #40)

 

Do you have a python/Pytorch implementation of the dequantization (/scaling) that is done at inference time?

**Comment by ylsung** [comment]
Is the `load_quip` (https://github.com/Cornell-RelaxML/quip-sharp/blob/b345d371cdc1af5b38675c48a0e8325f3c3d4a47/lib/utils/data_utils.py#L123) do the dequantization? I multiplied the generated `hatW` with inputs and the results are quite similar to using `quant_linear(inputs)`, but there was still a small difference though and I couldn't figure it out for now.

**Comment by tsengalb99** [comment]
load_quip just calls each codebook's by_idxs function. For E8P by_idxs just calls the cuda decompress. We haven't written a pure pytorch decompress for E8P yet. However, you can look at how the weights are packed in maybe_pack_idxs and write a function that reverses that packing.
