### ISSUE TITLE
NameError: name 'quant_emb' is not defined

### ISSUE THREAD

**Issue by eadst** [Cornell-RelaxML/quip-sharp#43]
File "/home/dong/code/quip-sharp/hessian_offline_llama.py", line 171, in main
    quant_emb[0:args.batch_size], 0).to(device)
NameError: name 'quant_emb' is not defined

Variable `quant_emb` is not defined in [hessian_offline_llama.py](https://github.com/Cornell-RelaxML/quip-sharp/blob/main/quantize_llama/hessian_offline_llama.py).

**Comment by tsengalb99** [comment]
thanks for catching this, I will fix it later this week

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dong ***@***.***>
Sent: Monday, February 19, 2024 10:35:54 PM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] NameError: name 'quant_emb' is not defined (Issue #43)


File "/home/dong/code/quip-sharp/hessian_offline_llama.py", line 171, in main
quant_emb[0:args.batch_size], 0).to(device)
NameError: name 'quant_emb' is not defined

Variable quant_emb is not defined in hessian_offline_llama.py<https://github.com/Cornell-RelaxML/quip-sharp/blob/main/quantize_llama/hessian_offline_llama.py>.

**Comment by tsengalb99** [comment]
@eadst if you replace quant_emb with dev_emb it should work. I'll merge in a fix soon but its a 2 line change.

**Comment by tsengalb99** [comment]
Yeah this bug is because I copied some code over from another file. There aren’t actually any functional changes from the old version so as long as you can generate the attention mask then the script should work.
