### ISSUE TITLE
3 bit quantization

### ISSUE THREAD

**Issue by timothelaborie** [Cornell-RelaxML/quip-sharp#5]
Does the method also work well with smaller codebooks that result in about 3 bits per weight?
Might be worth trying.

**Comment by tsengalb99** [comment]
The number of bits per weight is determined by the size of the codebook. It is definitely possible to expand the size of our E8 and D4 codebooks to achieve arbitrary bit values. We may release models quantized using such codebooks in the future, as this is an ongoing project.

**Comment by jerry-chee** [comment]
to add, it's also very straightforward to implement the half int codebook at b bits.

**Comment by oulin1031esti** [comment]
> The number of bits per weight is determined by the size of the codebook. It is definitely possible to expand the size of our E8 and D4 codebooks to achieve arbitrary bit values. We may release models quantized using such codebooks in the future, as this is an ongoing project.

Does the latest code support 3-bit quantization? If not, how should it be supported? Can _E8P_CODESZ be directly modified to achieve this?

**Comment by tsengalb99** [comment]
We are planning on releasing 3 and updated 4 bit models soon. Hopefully in a week or two.
