### ISSUE TITLE
[Question] Word Embedding Quantization?

### ISSUE THREAD

**Issue by 4eyes4u** [Cornell-RelaxML/quip-sharp#50]
Hello, I was wondering if we can apply the same approach for post-training quantization of word embeddings in transformer architecture. Usually, this word embedding module is demanding in size due to embedding map that is effectively large matrix of floats. What's your thoughts on this?

Thanks

**Comment by tsengalb99** [comment]
If you don't care about quantizing with the Hessian, then you can quantize the embedding layer by applying a RHT on the output side and quantizing it with the rest of the QuIP# method. I tried this before and it works reasonably well.
