### ISSUE TITLE
[Question] How to reproduce QuIP# (No FT & No E_8)

### ISSUE THREAD

**Issue by ChenMnZ** [Cornell-RelaxML/quip-sharp#52]
Hi,

I wonder that how can I reproduce the results of QuIP#(no FT and no lattice codebook E8).

`no lattice codebook E8` dose it mean uniform (INT) quantization, or is it still vector quantization.

**Comment by tsengalb99** [comment]
It means uniform scalar quantization. Specifically, for K bits, we round to the K bit grid [1/2, 3/2, … 2^K - 1/2] – 2^(K-1). You should be able to make a codebook class in lib/codebook that quantizes to this grid. You will need to determine the right scale. I have the code for this somewhere - ping me if you can’t implement a working codebook and I’ll try to find it.

 

From: Mengzhao Chen ***@***.***> 
Sent: Monday, April 8, 2024 10:32 PM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] [Question] How to reproduce QuIP# (No FT & No E_8) (Issue #52)

 

Hi,

I wonder that how can I reproduce the results of QuIP#(no FT and no lattice codebook E8).

no lattice codebook E8 dose it mean uniform (INT) quantization, or is it still vector quantization.

**Comment by ChenMnZ** [comment]
Thanks for your quick reply, I'll try it.
