### ISSUE TITLE
Question about the (L - I) term in LDLQ.

### ISSUE THREAD

**Issue by KimythAnly** [Cornell-RelaxML/quip-sharp#60]
Hi, thanks for your excellent work! I have a question about the LDLQ code :
https://github.com/Cornell-RelaxML/quip-sharp/blob/main/lib/algo/quip.py#L154
```python
        WXWX = Wr[:, (cb.codesz * k):(cb.codesz * (k + 1))] + \
            (Wr[:, (cb.codesz * (k + 1)):n] - hatWr[:, (cb.codesz * (k + 1)):n]) @ \
            L[(cb.codesz * (k + 1)):n, (cb.codesz * k):(cb.codesz * (k + 1))]
```
Could you please clarify whether this code results in `Q(Wr + (Wr - hatWr) @ L)` instead of `Q(Wr + (Wr - hatWr) @ (L - I))`? It seems like the code does not explicitly subtract the identity matrix from L.

Thank you!

**Comment by tsengalb99** [comment]
I may have accidentally deleted that line, let me take a look and get back to you. My private copy of the code does explicitly zero out the diagonal and I remember there was a line that did that at some point.

**Comment by tsengalb99** [comment]
I finally got a chance to look at this. `L[(cb.codesz * (k + 1)):n, (cb.codesz * k):(cb.codesz * (k + 1))]` does not include the I component of that column of L (L is lower triangular with block identity matrices along the diagonal) so it implicity does L-I. You can also explictly subtract I from L but that won't change anything.
