### ISSUE TITLE
    devset = utils.sample_rp1t(tokenizer, AttributeError: module 'lib.utils' has no attribute 'sample_rp1t'

### ISSUE THREAD

**Issue by LiMa-cas** [Cornell-RelaxML/quip-sharp#61]
devset = utils.sample_rp1t(tokenizer,
AttributeError: module 'lib.utils' has no attribute 'sample_rp1t'

how to solve this?

**Comment by tsengalb99** [comment]
That function should be here: https://github.com/Cornell-RelaxML/quip-sharp/blob/742af95b2ce68425423ec0a766fd67e0a5b5f73f/lib/utils/data_utils.py#L58. What file is the error showing up in?

**Comment by LiMa-cas** [comment]
thanks very much， i will check soon
















At 2024-07-13 09:26:28, "Albert Tseng" ***@***.***> wrote:

That function should be here: https://github.com/Cornell-RelaxML/quip-sharp/blob/742af95b2ce68425423ec0a766fd67e0a5b5f73f/lib/utils/data_utils.py#L58. What file is the error showing up in?
