### ISSUE TITLE
throughput question

### ISSUE THREAD

**Issue by leeglg** [Cornell-RelaxML/quip-sharp#63]
Hi, I saw your amazing paper. Thank you.

I have a question regarding the throughput presented in the paper.
Only throughput was presented in paper, would you mind telling me how many samples in batch, how many tokens per sample, and how many tokens you generated when measuring the throughput?

When I do the experiment with
 batch size 1, 
 600 tokens per each sample, 
 generating 128 tokens, 
I am not sure the kernel was used but it was nearly three times slower than the FP16 model, and the GPU utilization was around 9 to 12%.

**Comment by tsengalb99** [comment]
The reason why inference is slow with the `interactive_gen` script is because that script uses huggingface generate under the hood, and HF generate does not support cuda graphs. If you write your own generate function, then you should be able to use cuda graphs and get the advertised throughput.

**Comment by tsengalb99** [comment]
It seems like https://github.com/chu-tianxiang/QuIP-for-all rewrote the QuIP# code and is able to get ~140 tok/s with huggingface. I haven't verified if that repo is functionally correct, but the generation speed seems correct. QuIP# isn't tied to huggingface so you should also be able to integrate it with different frameworks (eg vllm).

**Comment by tsengalb99** [comment]
btw #65 has changes that support fast inference. I'm getting over 150 tok/s with torch 2.3.1 and over 160 tok/s with torch 2.4.0

**Comment by kim90000** [comment]
btw https://github.com/Cornell-RelaxML/quip-sharp/pull/65 has changes that support fast inference. I'm getting over 150 tok/s with torch 2.3.1 and over 160 tok/s with torch 2.4.0


how???????????????
