### ISSUE TITLE
.m16n8k8 nned cuda sm8.0 or higher

### ISSUE THREAD

**Issue by oreo0906** [Cornell-RelaxML/quip-sharp#64]
when I compile the .cu file on v100, the error occured, how to compile in lower gpu.

**Comment by nalzok** [comment]
Our code requires a GPU with compute capability 8.0 or higher, but V100 has compute capability 7.0, so it does not has the necessary hardware resources. You can use a newer GPU, such as A100.

**Comment by oreo0906** [comment]
if i don't have a gpu with compute capability 8.0. is there another method to replace .m16n8k16 instruction?



---- Replied Message ----
| From | Qingyao ***@***.***> |
| Date | 07/18/2024 23:26 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Cornell-RelaxML/quip-sharp] .m16n8k8 nned cuda sm8.0 or higher (Issue #64) |

Our code requires a GPU with compute capability 8.0 or higher, but V100 has compute capability 7.0, so it does not has the necessary hardware resources. You can use a newer GPU, such as A100.

**Comment by nalzok** [comment]
Technically it is possible, but practically speaking that's tricky since it requires changing the order in which we quantize the weights. See also this [relevant comment](https://github.com/Dao-AILab/flash-attention/issues/148#issuecomment-1574090582).
