### ISSUE TITLE
questions for # convert model to hf format for end to end fine tuning 

### ISSUE THREAD

**Issue by LiMa-cas** [Cornell-RelaxML/quip-sharp#66]
after quantize with finetuning， there are process of convert model to hf format for end to end fine tuning ，
I have  a question that if my llama2 model downloaded is hf format, do I need this process of convert model to hf format? generate hessians and quantize with finetuning would be influenced? thanks!

**Comment by tsengalb99** [comment]
The base model is already in the hf format so you don't need to convert it again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: LiMa-cas ***@***.***>
Sent: Monday, July 22, 2024 2:57:39 AM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] questions for # convert model to hf format for end to end fine tuning (Issue #66)


after quantize with finetuning， there are process of convert model to hf format for end to end fine tuning ，
I have a question that if my llama2 model downloaded is hf format, do I need this process of convert model to hf format? generate hessians and quantize with finetuning would be influenced? thanks!

**Comment by LiMa-cas** [comment]
thanks a lot ！ 




 so i could use hf model when generate hessians and quantize with finetuning ？













At 2024-07-22 10:31:56, "Albert Tseng" ***@***.***> wrote:

The base model is already in the hf format so you don't need to convert it again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: LiMa-cas ***@***.***>
Sent: Monday, July 22, 2024 2:57:39 AM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] questions for # convert model to hf format for end to end fine tuning (Issue #66)


after quantize with finetuning， there are process of convert model to hf format for end to end fine tuning ，
I have a question that if my llama2 model downloaded is hf format, do I need this process of convert model to hf format? generate hessians and quantize with finetuning would be influenced? thanks!

**Comment by tsengalb99** [comment]
Yes -- pass it in under the base model flag

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LiMa-cas** [comment]
do u have the E8 for llama3-8b-instruct？https://huggingface.co/relaxml，I find there no exits. In
 this case,could I get the E8 for llama3-8b-instruct by myself using the code? thanks a lot!!!

**Comment by LiMa-cas** [comment]
another question，for fine tuning process， do we need the datasets like qat？The distinction I'm not quite grasping is the difference between this fine-tuning and the fine-tuning performed during the training phase.

**Comment by LiMa-cas** [comment]
another question，sorry. When I use the "CUDA_VISIBLE_DEVICES=2 python3 quantize_llama/hessian_offline_llama.py --batch_size 4 --devset_size 6144 --ctx_size 2048 --base_model /extra_data/mali36/llama/Meta-Llama-3-8B-Instruct --save_path $HESS/Meta-Llama-3-8B-Instruct_6144 " problems occurs like"  envs/quip-sharp/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Bus error (core dumped)",How can I solve this?

**Comment by tsengalb99** [comment]
I haven't seen that error before but it might be an oom? You do need a dataset for fine tuning and Hessian generation. The paper has more details on how much data you need, but ~1000 samples of RP1T should be more than sufficient.
