### ISSUE TITLE
Reproducing the Results

### ISSUE THREAD

**Issue by mgholamikn** [Cornell-RelaxML/quip-sharp#67]
Hi,

Thank you for the great work. I tried reproducing the results by downloading `Llama-1-7b-E8P-2Bit` and using `eval/eval_ppl.py`. The PPL is very high around 100. Do you have any suggestion on what might be the reason? 

![image](https://github.com/user-attachments/assets/132df93e-418a-4de1-8760-60435ac568a5)

Thanks

**Comment by tsengalb99** [comment]
Hm that’s odd. Let me take a look later this week. Most likely there’s some huggingface version bug or maybe we forgot to update the llama 1 models when we changed the weight packing. Does Llama 2 7b 2 bit work fine for you? That’s the model I user for local testing so it should be up to date.

 

From: Mohsen Gholami ***@***.***> 
Sent: Tuesday, July 23, 2024 10:40 PM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] Reproducing the Results (Issue #67)

 

Hi,

Thank you for the great work. I tried reproducing the results by downloading Llama-1-7b-E8P-2Bit and using eval/eval_ppl.py. The PPL is very high around 100. Do you have any suggestion on what might be the reason?

image.png (view on web) <https://github.com/user-attachments/assets/132df93e-418a-4de1-8760-60435ac568a5> 

Thanks

**Comment by mgholamikn** [comment]
Thanks a lot for the prompt reply. Yes, sounds like the problem is with Llama-1 models. I also tried `Llama-1-7b-E8PRVQ-3Bit` and the PPL is more than 100. However, the llama-2 model is good. This is the results of `Llama-2-7b-E8P-2Bit`:

![image](https://github.com/user-attachments/assets/722ef45b-ef6a-4891-851c-70bac0c6c758)

Could you please update the Llama-1 models on huggingface? Thanks!

**Comment by tsengalb99** [comment]
I'll do that after ICML or maybe @nalzok can take a look now.

**Comment by tsengalb99** [comment]
Sorry, haven't had time to get to this yet. You may find it faster to requantize the Llama 1 models with the codebase. 7B should only take 10 minutes to quantize on 8 A100s, or an hour or two on one GPU.

**Comment by tsengalb99** [comment]
@mgholamikn do you still need quantized Llama 1 models? I've had way too much stuff on my plate and still have not gotten around to this.

**Comment by mgholamikn** [comment]
Thanks for the follow-up. I am using Llama2 for now. I did quantize llama1 with your code. I haven't tested it yet
