### ISSUE TITLE
Question about the paper.

### ISSUE THREAD

**Issue by jhss** [Cornell-RelaxML/quip-sharp#70]
Hello.

In the section 4, the author said that

> rounding weights one at a time, as QuIP does with its LDLQ, ignores this shaping—producing a set of representable weight vectors that is shaped like a hypercube rather than a ball.

I don't understand why LDLQ produces a set of vectors shaped like a hypercube and BlockLDLQ produces a set of vectors like ball. Is there any additional explanation or reference related with the shape with LDLQ?

Thank you.

**Comment by jerry-chee** [comment]
This paper: https://arxiv.org/pdf/2402.15319, Fig 1 has a nice explanation

**Comment by tsengalb99** [comment]
To clarify, Block/LDLQ is not the thing that results in ball shaped weights. Incoherence processing with the Hadamard transform results in approximately i.i.d Gaussian weights, which means they are also jointly Gaussian. Scalar quantization can only take limited advantage of this shaping, VQ can do more (see the paper Jerry linked or https://arxiv.org/abs/1102.3944). BlockLDLQ is just a variant of LDLQ that supports vector quantization, but the shaping advantage comes from VQ, not LDLQ.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
