### ISSUE TITLE
Can we run the kernels on V100 machines?

### ISSUE THREAD

**Issue by mgholamikn** [Cornell-RelaxML/quip-sharp#71]
Hi,

Thank you for your great work and nice repo. I was able to run the code on an A100 machine but had difficulties running it on a V100 machine. I was wondering if the kernels are runnable on V100 machines. 

Thanks

**Comment by tsengalb99** [comment]
I think someone opened a ticket about this before. IIRC the MMA tile shape we use is not supported on the V100. It is probably possible to write the kernel to support V100s, but that is not a high priority for us. You are more than welcome to try to patch our kernel to support V100s though.

 

From: Mohsen Gholami ***@***.***> 
Sent: Tuesday, August 27, 2024 4:07 PM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] Can we run the kernels on V100 machines? (Issue #71)

 

Hi,

Thank you for your great work and nice repo. I was able to run the code on an A100 machine but had difficulties running it on a V100 machine. I was wondering if the kernels are runnable on V100 machines.

Thanks

**Comment by mgholamikn** [comment]
Thanks for the reply. Is there an easy way to do fake quantization and bypass the kernel at the inference to check the PPL?

**Comment by tsengalb99** [comment]
Yes, we used to have a function in the codebase to do that before we added a data permutation for the kernel. If you dig through commits from last year you might find it. I can look for it in my private codebase later this week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mgholamikn** [comment]
Could you please help me with this? I could not find the fake quantization in last year's commits.

**Comment by tsengalb99** [comment]
Sorry I totally forgot to response. I will try to write one at some point when I find time but you may just want to call the dequantize kernel without the matvec since the volta error is with the MMA tile and not the actual decompression function.

**Comment by tsengalb99** [comment]
You should be able to comment out the matvec kernel, compile only the decode kernel, and then call that like we do here. https://github.com/Cornell-RelaxML/quip-sharp/blob/d12f479daf3a63ed2841dd00d4f4d222cafa739b/lib/codebook/latticee8_padded12.py#L286

**Comment by mgholamikn** [comment]
Thanks for your reply
