### ISSUE TITLE
llama 3 8b results 

### ISSUE THREAD

**Issue by dorsa-zeinali** [Cornell-RelaxML/quip-sharp#72]
Hi, 
I am reproducing your work, and does 50.69% accuracy for hellaswag benchmark and 9.095 ppl for wikitext 2 for llama 3 8b make sense? To be able to run the computation on my resources, I reduced the context size to 600 for all steps. Please let me know. Thank you!

**Comment by tsengalb99** [comment]
I'm not sure about hellaswag but the perplexity number seems reasonable for a context length of 600. The QTIP paper https://arxiv.org/abs/2406.11235 has the results we got for Llama 3 and QuIP#; there we got around 8 perplexity.

**Comment by dorsa-zeinali** [comment]
thank you
