### ISSUE TITLE
what the fuction of （finetune_decoder_layer） for？

### ISSUE THREAD

**Issue by LiMa-cas** [Cornell-RelaxML/quip-sharp#73]
hi，I have read the code， but I don't know what the finetune_decoder_layer, which parames does it funtuned? su and sv parameters?
what is su and sv parameters?

**Comment by tsengalb99** [comment]
finetune_decoder_layer finetunes unquantized parameters before they are quantized and unquantized parameters that will not be quantized at all (eg SU/SV). SU and SV are the sign vectors for the random Hadamard transform -- they do not need to be sign vectors after the matrix is quantized so we can tune them.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: LiMa-cas ***@***.***>
Sent: Monday, September 2, 2024 3:16:26 PM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] what the fuction of （finetune_decoder_layer） for？ (Issue #73)


hi，I have read the code， but I don't know what the finetune_decoder_layer, which parames does it funtuned? su and sv parameters?
what is su and sv parameters?

**Comment by LiMa-cas** [comment]
thanks a lot. So if I use this fuction on AWQ, what parameters should  i finetuen?

**Comment by tsengalb99** [comment]
AWQ is a totally different quantization method from QuIP#, so I am not sure what method-specific parameters you can tune there. However, the general "tune before you quantize" fine tuning method in QuIP# should work without modification with AWQ. There, you would quantize a linear layer with AWQ, fine tune the unquantized layers to compensate for the error of the quantized layer, then go on to the next linear layer and repeat.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LiMa-cas** [comment]
thanks a lot

**Comment by tsengalb99** [comment]
SU and SV are the sign vectors in the paper. QuIP# supports Llama 3, but I have not prequantized any Llama 3 models yet.

**Comment by LiMa-cas** [comment]
thanks，what about the speed of 4bit？

**Comment by LiMa-cas** [comment]
![{3C1A6084-AFC9-4040-862B-C9C528F7177D}](https://github.com/user-attachments/assets/e043c9bf-01b9-48ee-90c5-766572b16f11)
Hi，I use the python -m quantize_llama.hessian_offline_llama --batch_size 4 --devset_size 6144 --ctx_size 2048 --base_model /extra_data/mali36/llama/llama3-8B-instrut --save_path $HESS/llama3_8b_6144，there are problems
