### ISSUE TITLE
QwenVL quantization

### ISSUE THREAD

**Issue by lzd19981105** [Cornell-RelaxML/quip-sharp#77]
I have migrated the method to the qwenvl model and evaluated it using VLMEvalKit for certain visual tasks under the int2 condition. The specific link is as follows:[quip-sharp-qwenvl](https://github.com/lzd19981105/quip-sharp-qwenvl/tree/main)，Welcome to provide corrections.

**Comment by tsengalb99** [comment]
Exciting! Looking forward to seeing the results. We also have an updated method, QTIP (https://github.com/Cornell-RelaxML/qtip), that performs better than QuIP# while being just as fast. You may want to QTIP QwenVL too.

**Comment by lzd19981105** [comment]
我公开了QwenVL在GPTQ-W4A16/GPTQ-W3A16/QUIP#-W2A16量化条件下在部分视觉语言任务上的结果！
